configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
 
# restore NuGet packages before running MSBuild
build_script:
  - ps: Get-Content '.\Extensions\JamesDibble.Extensions.System\Properties\AssemblyInfo.cs'

test: off

